const $=s=>document.querySelector(s), dbReq=indexedDB.open('moneylog-db',1);
let db,tab='home',hide=false,transactions=[],accounts=[],budget=0,editing=null;
dbReq.onupgradeneeded=()=>{let d=dbReq.result;d.createObjectStore('transactions',{keyPath:'id',autoIncrement:true});d.createObjectStore('accounts',{keyPath:'id',autoIncrement:true});d.createObjectStore('settings')};
dbReq.onsuccess=()=>{db=dbReq.result;init()};
const store=(n,mode='readonly')=>db.transaction(n,mode).objectStore(n);
function all(n){return new Promise(r=>{let q=store(n).getAll();q.onsuccess=()=>r(q.result)})}
function put(n,v){return new Promise((r,j)=>{let q=store(n,'readwrite').put(v);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)})}
function add(n,v){return new Promise((r,j)=>{let q=store(n,'readwrite').add(v);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)})}
function del(n,id){return new Promise(r=>{let q=store(n,'readwrite').delete(id);q.onsuccess=r})}
const money=n=>'৳'+(Number(n||0)/100).toLocaleString('en-BD',{minimumFractionDigits:2,maximumFractionDigits:2});
const today=()=>new Date().toISOString().slice(0,10), month=()=>today().slice(0,7);
async function init(){accounts=await all('accounts');if(!accounts.length){await add('accounts',{name:'Cash',opening:0,type:'Cash'});accounts=await all('accounts')}transactions=await all('transactions');budget=await new Promise(r=>{let q=store('settings').get('budget');q.onsuccess=()=>r(q.result||0)});render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
function balance(id){let a=accounts.find(x=>x.id===id);return (a?.opening||0)+transactions.reduce((s,t)=>s+(t.type==='income'&&t.account===id?t.amount:t.type==='expense'&&t.account===id?-t.amount:t.type==='transfer'&&t.from===id?-t.amount:t.type==='transfer'&&t.to===id?t.amount:0),0)}
function totals(){let m=month(),ts=transactions.filter(t=>t.date?.startsWith(m));return {inc:ts.filter(t=>t.type==='income').reduce((s,t)=>s+t.amount,0),exp:ts.filter(t=>t.type==='expense').reduce((s,t)=>s+t.amount,0)}}
function render(){let v=$('#view');if(tab==='home'){let t=totals(),bal=accounts.reduce((s,a)=>s+balance(a.id),0);v.innerHTML=`<div class="eyebrow">YOUR MONEY, AT A GLANCE</div><section class="balance"><div class="row"><span class="eyebrow" style="color:#c2d5cc">TOTAL BALANCE</span><button class="ghost" id="visibility">${hide?'Show':'Hide'} amounts</button></div><div class="amount">${hide?'••••••':money(bal)}</div><small style="color:#c2d5cc">${accounts.length} account${accounts.length===1?'':'s'}</small></section><div class="grid"><div class="card"><div class="eyebrow">INCOME · THIS MONTH</div><div class="metric positive">${hide?'••••':money(t.inc)}</div></div><div class="card"><div class="eyebrow">EXPENSE · THIS MONTH</div><div class="metric negative">${hide?'••••':money(t.exp)}</div></div></div>${budget?`<div class="card"><div class="row"><b>Monthly budget</b><b>${hide?'••••':money(Math.max(0,budget-t.exp))} left</b></div><div class="bar"><span style="width:${Math.min(100,t.exp/budget*100)}%"></span></div><small class="muted">${money(t.exp)} of ${money(budget)}</small></div>`:''}<div class="section row"><h2>Recent transactions</h2><button class="link" id="allhistory">See all</button></div>${list(transactions.slice().sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id).slice(0,5))}<button class="fab" id="add">＋</button>`;$('#visibility').onclick=()=>{hide=!hide;render()};$('#add').onclick=()=>form();$('#allhistory').onclick=()=>{tab='history';render();nav()};wireRows()}
else if(tab==='history'){v.innerHTML=`<h1>History</h1><input id="search" placeholder="Search notes, category, account…" style="width:100%;padding:13px;border:1px solid var(--line);border-radius:12px"><div id="historylist" class="section"></div><button class="fab" id="add">＋</button>`;$('#add').onclick=()=>form();$('#search').oninput=e=>historyList(e.target.value);historyList('')}
else if(tab==='insights'){let t=totals(),cats={};transactions.filter(x=>x.type==='expense'&&x.date.startsWith(month())).forEach(x=>cats[x.category]=(cats[x.category]||0)+x.amount);let max=Math.max(1,...Object.values(cats));v.innerHTML=`<h1>Insights</h1><div class="grid"><div class="card"><div class="eyebrow">INCOME · THIS MONTH</div><div class="metric positive">${money(t.inc)}</div></div><div class="card"><div class="eyebrow">EXPENSE · THIS MONTH</div><div class="metric negative">${money(t.exp)}</div></div></div><div class="card"><h2>Spending by category</h2>${Object.entries(cats).sort((a,b)=>b[1]-a[1]).map(([c,n])=>`<div class="field"><div class="row"><b>${esc(c)}</b><span>${money(n)}</span></div><div class="bar"><span style="width:${n/max*100}%"></span></div></div>`).join('')||'<div class="empty">Add expenses to see your spending breakdown.</div>'}</div><div class="card"><h2>Accounts</h2>${accounts.map(a=>`<div class="row item"><span>${esc(a.name)}</span><b>${money(balance(a.id))}</b></div>`).join('')}</div>`}
else settingsView();document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab))}
function nav(){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab))}
function list(ts){if(!ts.length)return '<div class="empty">No transactions yet.<br>Add your first entry to get started.</div>';return ts.map(t=>`<div class="item" data-id="${t.id}"><div class="bubble">${t.type==='income'?'↙':t.type==='expense'?'↗':'⇄'}</div><div class="detail"><strong>${esc(t.category||'Transfer')}</strong><small>${esc(t.note||t.type)} · ${esc(accounts.find(a=>a.id===t.account)?.name||'Account')} · ${t.date}</small></div><span class="amount ${t.type==='income'?'positive':t.type==='expense'?'negative':''}">${t.type==='expense'?'−':t.type==='income'?'+':''}${money(t.amount)}</span></div>`).join('')}
function wireRows(){document.querySelectorAll('.item[data-id]').forEach(el=>el.onclick=()=>form(transactions.find(t=>t.id===+el.dataset.id)))}
function historyList(q){let ts=transactions.slice().sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id).filter(t=>(t.note+' '+t.category+' '+t.type+' '+(accounts.find(a=>a.id===t.account)?.name||'')).toLowerCase().includes(q.toLowerCase()));$('#historylist').innerHTML=list(ts);wireRows()}
function open(html){$('#modal').innerHTML=`<div class="sheet">${html}</div>`;$('#modal').classList.remove('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')close()}}
function close(){$('#modal').classList.add('hidden')}
function form(t){editing=t||null;let type=t?.type||'expense';open(`<div class="row"><h2>${t?'Edit':'New'} transaction</h2><button class="link" id="close">✕</button></div><div class="type-switch">${['expense','income','transfer'].map(x=>`<button data-type="${x}" class="${x===type?'chosen':''}">${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</div><form id="txform"><div class="field"><label>Amount (BDT)</label><input name="amount" type="number" min="0.01" step="0.01" required inputmode="decimal" placeholder="0.00" value="${t?(t.amount/100):''}"></div><div class="field" id="categoryfield"><label>Category</label><input name="category" value="${esc(t?.category||'')}" placeholder="${type==='income'?'Salary':'Food'}" required></div><div class="field" id="accountfield"><label>Account</label><select name="account">${accounts.map(a=>`<option value="${a.id}" ${t?.account===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select></div><div class="field ${type==='transfer'?'':'hidden'}" id="tofield"><label>To account</label><select name="to">${accounts.map(a=>`<option value="${a.id}" ${t?.to===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select></div><div class="field"><label>Date</label><input name="date" type="date" value="${t?.date||today()}" required></div><div class="field"><label>Note (optional)</label><input name="note" value="${esc(t?.note||'')}" placeholder="What was this for?"></div><div class="actions"><button type="button" class="link" id="cancel">Cancel</button><button class="primary">Save transaction</button></div>${t?'<button type="button" class="link" id="delete" style="color:var(--red);width:100%;margin-top:10px">Delete transaction</button>':''}</form>`);
$('#close').onclick=$('#cancel').onclick=close;document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{let x=b.dataset.type;form({...t,type:x})});$('#txform').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),amount=Math.round(Number(f.get('amount'))*100),ty=type;if(!Number.isSafeInteger(amount)||amount<=0)return alert('Enter a valid amount.');let obj={...(t||{}),type:ty,amount,category:ty==='transfer'?'Transfer':f.get('category').trim(),account:+f.get('account'),to:+f.get('to'),date:f.get('date'),note:f.get('note').trim()};if(ty==='transfer'&&obj.account===obj.to)return alert('Choose two different accounts.');if(t)await put('transactions',obj);else await add('transactions',obj);transactions=await all('transactions');close();render()};if(t)$('#delete').onclick=async()=>{if(confirm('Delete this transaction?')){await del('transactions',t.id);transactions=await all('transactions');close();render()}}}
function settingsView(){ $('#view').innerHTML=`<h1>Settings</h1><div class="card"><h2>Accounts</h2>${accounts.map(a=>`<div class="item"><div class="detail"><b>${esc(a.name)}</b><small>${a.type}</small></div><b>${money(balance(a.id))}</b></div>`).join('')}<button class="primary" id="accountadd">＋ Add account</button></div><div class="card"><h2>Monthly budget</h2><div class="field"><label>Overall spending limit (BDT)</label><input id="budget" type="number" min="0" step=".01" value="${budget/100}"></div><button class="primary" id="savebudget">Save budget</button></div><div class="card"><h2>Backup & restore</h2><p class="muted">Encrypted file, protected by a password you choose.</p><button class="primary" id="export">Export encrypted backup</button><div class="field"><label>Restore a .moneylog file</label><input id="backupfile" type="file" accept=".moneylog,application/octet-stream"></div></div><div class="card"><h2>Privacy</h2><p class="muted">Your records stay in this browser on this device. No account or server is used.</p><button class="link" id="wipe" style="color:var(--red)">Delete all MONEYLOG data</button></div>`;$('#accountadd').onclick=()=>open(`<h2>Add account</h2><form id="af"><div class="field"><label>Account name</label><input name="name" required placeholder="e.g. Bank"></div><div class="field"><label>Opening balance (BDT)</label><input name="opening" type="number" step=".01" value="0"></div><div class="actions"><button type="button" class="link" onclick="document.querySelector('#modal').classList.add('hidden')">Cancel</button><button class="primary">Save</button></div></form>`);$('#af').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);await add('accounts',{name:f.get('name').trim(),opening:Math.round(+f.get('opening')*100),type:'Account'});accounts=await all('accounts');close();render()};$('#savebudget').onclick=async()=>{budget=Math.round(Math.max(0,+$('#budget').value)*100);await put('settings',{key:'budget',value:budget});render()};$('#export').onclick=backupExport;$('#backupfile').onchange=e=>backupImport(e.target.files[0]);$('#wipe').onclick=async()=>{if(confirm('Permanently delete all MONEYLOG data? This cannot be undone.')){for(let n of ['transactions','accounts','settings'])await new Promise(r=>{let q=db.transaction(n,'readwrite').objectStore(n).clear();q.onsuccess=r});location.reload()}}}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function backupExport(){let pw=prompt('Choose a password for this backup (at least 8 characters):');if(!pw)return;if(pw.length<8)return alert('Use at least 8 characters.');let payload=JSON.stringify({version:1,created:new Date().toISOString(),transactions,accounts,budget}),salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await derive(pw,salt),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(payload));let blob=new Blob([JSON.stringify({magic:'MONEYLOG',version:1,salt:b64(salt),iv:b64(iv),data:b64(new Uint8Array(cipher))})],{type:'application/octet-stream'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='moneylog-backup.moneylog';a.click();URL.revokeObjectURL(a.href)}
async function backupImport(file){if(!file)return;try{let pw=prompt('Enter the backup password:');if(!pw)return;let b=JSON.parse(await file.text());if(b.magic!=='MONEYLOG'||b.version!==1)throw Error('Unsupported backup');let plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(b.iv)},await derive(pw,unb64(b.salt)),unb64(b.data)),data=JSON.parse(new TextDecoder().decode(plain));if(!confirm('Replace all current MONEYLOG data with this backup?'))return;for(let [n,arr] of [['transactions',data.transactions],['accounts',data.accounts]]){await new Promise(r=>{let q=db.transaction(n,'readwrite').objectStore(n).clear();q.onsuccess=r});for(let x of arr)await put(n,x)}budget=data.budget||0;await put('settings',{key:'budget',value:budget});await init();alert('Backup restored.')}catch(e){alert('Could not restore this backup. Check the password and file integrity.')}} 
async function derive(p,salt){let base=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}const b64=a=>btoa(String.fromCharCode(...a));const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install').hidden=false});$('#install').onclick=async()=>{if(installPrompt){installPrompt.prompt();installPrompt=null}else alert('Use your browser menu and choose Add to Home Screen.');};
